export const error = {
    SETERROR: 'SETERROR',
    CLEARERROR: 'CLEARERROR'
};

export const ingredient = {
    START: 'INGREDIENTSTART',
    SUCCESS: 'INGREDIENTSUCCESS',
    FAIL: 'INGREDIENTFAIL',
    CLEAR: 'INGREDIENTCLEAR',
    RESET: 'INGREDIENTRESET',
    SET: 'INGREDIENTSET',
    EDIT: 'INGREDIENTEDIT',
    EDITCANCEL: 'INGREDIENTEDITCANCEL',
    CHANGE: 'INGREDIENTCHANGE',
    RETRIEVE: 'INGREDIENTRETRIEVE',
    VALID: 'INGREDIENTVALID',
    CREATE: 'INGREDIENTCREATE'
};

export const lookup = {
    START: 'LOOKUPSTART',
    SUCCESS: 'LOOKUPSUCCESS',
    FAIL: 'LOOKUPFAIL'
}

export const media = {
    START: 'MEDIASTART',
    SUCCESS: 'MEDIASUCCESS',
    FAIL: 'MEDIAFAIL',
    CLEAR: 'MEDIACLEAR',
    EDITCANCEL: 'MEDIAEDITCANCEL',
    RESET: 'MEDIARESET'
};

export const method = {
    START: 'METHODSTART',
    SUCCESS: 'METHODSUCCESS',
    FAIL: 'METHODFAIL',
    CLEAR: 'METHODCLEAR',
    RESET: 'METHODRESET',
    SET: 'METHODSET',
    EDIT: 'METHODEDIT',
    EDITCANCEL: 'METHODEDITCANCEL',
    CHANGE: 'METHODCHANGE',
    RETRIEVE: 'METHODRETRIEVE',
    VALID: 'METHODVALID',
    CREATE: 'METHODCREATE'
};

export const search = {
    CLEAR: 'SEARCHCLEAR',
    START: 'SEARCHSTART',
    SUCCESS: 'SEARCHSUCCESS',
    FAIL: 'SEARCHFAIL',
    SETCRITERIA: 'SETCRITERIA',
    SETRESEARCH: 'SETRESEARCH',
    RESET: 'SEARCHRESET'
};

export const status = {
    TIME: 'STATUSTIME',
    CLEAR: 'STATUSCLEAR',
    START: 'STATUSSTART',
    SUCCESS: 'STATUSSUCCESS',
    FAIL: 'STATUSFAIL',    
    EXPIRES: 'STATUSEXPIRES',
    TOEXPIRE: 'STATUSTOEXPIRE',
    RESET: 'STATUSRESET'
};

export const authenticate = {
    SET: 'AUTHENTICATIONSET',
    SETVALID: 'AUTHENTICATIONSETVALID',
    START: 'AUTHENTICATIONSTART',
    SUCCESS: 'AUTHENTICATIONSUCCESS',
    FAIL: 'AUTHENTICATIONFAIL',
    RESET: 'AUTHENTICATIONRESET'
};

export const recipe = {
    SETTAB: 'RECIPESETTAB',
    START: 'RECIPESTART',
    SUCCESS: 'RECIPESUCCESS',
    FAIL: 'RECIPEFAIL',
    EDIT: 'RECIPEEDIT',
    EDITCANCEL: 'RECIPEEDITCANCEL',
    DELETE: 'RECIPEDELETE',
    CHANGE: 'RECIPECHANGE',
    CLEAR: 'RECIPECLEAR',
    CREATE: 'RECIPECREATE',
    CREATECANCEL: 'RECIPECREATECANCEL',
    SETVALID: 'RECIPESETVALID',
    RESET: 'RECIPERESET'
};

export const popup = {
    ACTIVATE: 'POPUPACTIVATE',
    INACTIVATE: 'POPUPINACTIVATE',
    MOVE: 'POPUPMOVE',
    OPEN: 'POPUPOPEN'
};